server:
  port: 8080
springdoc:
  api-docs:
    path: '/v1/docs'
  swagger-ui:
    path: '/v1/swagger'
    disable-swagger-default-url: true
    display-request-duration: true

apis:
  subscription_api_url: 'http://localhost:8081/adidas-subscriptions-service/v1/'