server:
  port: 8080
springdoc:
  api-docs:
    path: '/${api.version}/docs'
  swagger-ui:
    path: '${api.version}/swagger'
    disable-swagger-default-url: true
    display-request-duration: true

apis:
  subscription_api_url: 'http://localhost:8081/adidas-subscriptions-service/v1/'