name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'main'
      - 'release*'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Gradle Package
        run: gradle clean build -x test
      - name: Gradle Verify
        run: gradle clean test